# fly.toml app configuration file generated for talishar-beta on 2023-09-16T14:03:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "talishar-beta"
primary_region = "sin"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "beta.Dockerfile"

[env]
  PHP_FPM_CLEAR_ENV = "no"
  MYSQL_SERVER_NAME = "talishar-beta-mysql.internal"
  MYSQL_SERVER_USER_NAME = "root"
  REDIS_ENABLED = "false"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
   
[[services.ports]]
  handlers = ["http"]
  port = 443
  force_https = true  # optional
